/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture, useVideoTexture } from '@react-three/drei'
import { gsap } from 'gsap'
import { useGSAP } from '@gsap/react'

const DEFAULT_URL =
  'https://raw.githubusercontent.com/Joanne0119/portfolio/main/public/projects/MarketDuckDemo.mp4'

const isVideoUrl = (url) => /\.(mp4|webm|mov|m4v)(\?|#|$)/i.test(url || '')

const CellphoneBody = ({ txt, groupProps }) => {
  const phoneRef = useRef()
  const { nodes, materials } = useGLTF('/models/phone.glb')

  useGSAP(() => {
    if (!phoneRef.current) return
    gsap.to(phoneRef.current.position, {
      y: phoneRef.current.position.y + 0.2,
      duration: 1.2,
      repeat: -1,
      yoyo: true,
    })
  })

  return (
    <group {...groupProps} dispose={null} ref={phoneRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_13.geometry}
        material={materials.phone_body}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Screen}
      >
        <meshBasicMaterial map={txt} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Black}
      />
    </group>
  )
}

const VideoCellphone = ({ url, groupProps }) => {
  const txt = useVideoTexture(url, {
    loop: true,
    muted: true,
    start: true,
    crossOrigin: 'Anonymous',
  })
  return <CellphoneBody txt={txt} groupProps={groupProps} />
}

const ImageCellphone = ({ url, groupProps }) => {
  const txt = useTexture(url)
  return <CellphoneBody txt={txt} groupProps={groupProps} />
}

const Cellphone = ({ texture, ...groupProps }) => {
  const url = texture || DEFAULT_URL
  return isVideoUrl(url) ? (
    <VideoCellphone url={url} groupProps={groupProps} />
  ) : (
    <ImageCellphone url={url} groupProps={groupProps} />
  )
}

useGLTF.preload('/models/phone.glb')
export default Cellphone
