/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const CodingAvatar = (props)  => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/codingAvatar.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <skinnedMesh
            name="body"
            geometry={nodes.body.geometry}
            material={materials['purpule shirt']}
            skeleton={nodes.body.skeleton}
          />
          <skinnedMesh
            name="hands"
            geometry={nodes.hands.geometry}
            material={materials.Skin}
            skeleton={nodes.hands.skeleton}
          />
          <skinnedMesh
            name="head_1"
            geometry={nodes.head_1.geometry}
            material={materials.Face}
            skeleton={nodes.head_1.skeleton}
          />
          <skinnedMesh
            name="legs"
            geometry={nodes.legs.geometry}
            material={materials.Jeans}
            skeleton={nodes.legs.skeleton}
          />
          <skinnedMesh
            name="neck_1"
            geometry={nodes.neck_1.geometry}
            material={materials.Skin}
            skeleton={nodes.neck_1.skeleton}
          />
          <skinnedMesh
            name="shirtArms"
            geometry={nodes.shirtArms.geometry}
            material={materials['purpule shirt']}
            skeleton={nodes.shirtArms.skeleton}
          />
          <skinnedMesh
            name="shoes"
            geometry={nodes.shoes.geometry}
            material={materials.shoe}
            skeleton={nodes.shoes.skeleton}
          />
          <primitive object={nodes.torso} />
          <primitive object={nodes.hand_controlL} />
          <primitive object={nodes.elbowL} />
          <primitive object={nodes.hand_controlR} />
          <primitive object={nodes.elbowR} />
          <primitive object={nodes.kneeL} />
          <primitive object={nodes.leg_controlL} />
          <primitive object={nodes.kneeR} />
          <primitive object={nodes.leg_controlR} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/codingAvatar.glb')

export default CodingAvatar
