/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { gsap } from "gsap";
import { useGSAP } from '@gsap/react';

const GraduationHat = (props) => {

    const hatRef = useRef();

    useGSAP(() => {
      gsap.to(hatRef.current.position, {
        y: hatRef.current.position.y + 1,
        duration: 1.2,
        repeat: -1,
        yoyo: true,
      })
      gsap.to(hatRef.current.rotation, {
          x: `${Math.PI / 9}`,
          duration: 1.2,
          repeat: -1,
          yoyo: true,
      })
   });
   
  const { nodes, materials } = useGLTF('../public/models/GraduationHat.glb')
  return (
    <group {...props} dispose={null} ref={hatRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.top.geometry}
        material={materials.hat}
        position={[0, -0.495, 0]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={[0.564, 0.133, 0.564]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bottom.geometry}
        material={materials.hat}
        position={[0, 0, 0]}
        rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
        scale={[0.4, 0.141, 0.4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.line.geometry}
        material={materials.yellow}
        position={[-0.671, -0.206, 0]}
        scale={[-0.018, -0.249, -0.024]}
      />
    </group>
  )
}

useGLTF.preload('../public/models/GraduationHat.glb')

export default GraduationHat