/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three' 

const HiAvatar = ({animationName = 'Idel', ...props}) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/hiavatar.glb')
  const { actions, mixer } = useAnimations(animations, group)

  const [activeAction, setActiveAction] = useState(null)

  useEffect(() => {
    console.log(actions);
    console.log(animationName);
    if (actions && animationName) {
      if (activeAction && actions[activeAction]) {
        actions[activeAction].fadeOut(0.5);
      }
      if (actions[animationName]) {
        const currentAction = actions[animationName]
        currentAction.reset()
        currentAction.setLoop(THREE.LoopOnce)  // Play animation only once
        currentAction.clampWhenFinished = true // Stop at the last frame when finished
        currentAction.play()

        // Optional: Add an event listener to detect when the action ends
        currentAction.getMixer().addEventListener('finished', () => {
          // Once animation finishes, reset to Idle if not hovering
          if (animationName !== 'Idel') {
            actions['Idel']?.reset().fadeIn(0.5).play()
          }
        })

        setActiveAction(animationName)
      }
    }
  }, [actions, animationName, activeAction]);
  
  useFrame((_, delta) => mixer.update(delta))

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_0" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="root_1">
                  <group name="GLTF_SceneRootNode_2" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Armature_33_3">
                      <group name="GLTF_created_0_4">
                        <group name="GLTF_created_0">
                          <primitive object={nodes.GLTF_created_0_rootJoint} />
                          <skinnedMesh
                            name="Object_41"
                            geometry={nodes.Object_41.geometry}
                            material={materials.purpule_shirt}
                            skeleton={nodes.Object_41.skeleton}
                          />
                          <skinnedMesh
                            name="Object_44"
                            geometry={nodes.Object_44.geometry}
                            material={materials.Skin}
                            skeleton={nodes.Object_44.skeleton}
                          />
                          <skinnedMesh
                            name="Object_47"
                            geometry={nodes.Object_47.geometry}
                            material={materials.Face}
                            skeleton={nodes.Object_47.skeleton}
                          />
                          <skinnedMesh
                            name="Object_50"
                            geometry={nodes.Object_50.geometry}
                            material={materials.Jeans}
                            skeleton={nodes.Object_50.skeleton}
                          />
                          <skinnedMesh
                            name="Object_53"
                            geometry={nodes.Object_53.geometry}
                            material={materials.Skin}
                            skeleton={nodes.Object_53.skeleton}
                          />
                          <skinnedMesh
                            name="Object_56"
                            geometry={nodes.Object_56.geometry}
                            material={materials.purpule_shirt}
                            skeleton={nodes.Object_56.skeleton}
                          />
                          <skinnedMesh
                            name="Object_59"
                            geometry={nodes.Object_59.geometry}
                            material={materials.shoe}
                            skeleton={nodes.Object_59.skeleton}
                          />
                          <group name="Object_7_7_correction">
                            <group name="Object_7_7" />
                          </group>
                          <group name="Object_9_9_correction">
                            <group name="Object_9_9" />
                          </group>
                          <group name="Object_11_11_correction">
                            <group name="Object_11_11" />
                          </group>
                          <group name="Object_13_13_correction">
                            <group name="Object_13_13" />
                          </group>
                          <group name="Object_15_15_correction">
                            <group name="Object_15_15" />
                          </group>
                          <group name="Object_17_17_correction">
                            <group name="Object_17_17" />
                          </group>
                          <group name="Object_19_19_correction">
                            <group name="Object_19_19" />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/hiavatar.glb')

export default HiAvatar
