/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture, useVideoTexture } from '@react-three/drei'
import { gsap } from 'gsap'
import { useGSAP } from '@gsap/react'

const DEFAULT_URL =
  'https://raw.githubusercontent.com/Joanne0119/portfolio/main/public/projects/PortfolioDemo.mp4'

const isVideoUrl = (url) => /\.(mp4|webm|mov|m4v)(\?|#|$)/i.test(url || '')

const MacbookBody = ({ txt, groupProps }) => {
  const macRef = useRef()
  const { nodes, materials } = useGLTF('/models/computer.glb')

  useGSAP(() => {
    if (!macRef.current) return
    gsap.to(macRef.current.position, {
      y: macRef.current.position.y + 0.2,
      duration: 1.2,
      repeat: -1,
      yoyo: true,
    })
  })

  return (
    <group {...groupProps} dispose={null} ref={macRef}>
      <group position={[0, 0.294, -0.604]} rotation={[-0.247, 0, 0]} scale={[1, 1.073, 1]}>
        <mesh castShadow receiveShadow geometry={nodes.Cube015.geometry} material={materials.Mac} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials.Mac_Black}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.keyboard.geometry}
        material={materials.Mac}
        position={[0, 0.294, -0.604]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.963, 1, 1]}
      />
      <mesh castShadow receiveShadow geometry={nodes.Screen.geometry} material={materials.dot}>
        <meshBasicMaterial map={txt} />
      </mesh>
    </group>
  )
}

const VideoMacbook = ({ url, groupProps }) => {
  const txt = useVideoTexture(url, {
    loop: true,
    muted: true,
    start: true,
    crossOrigin: 'Anonymous',
  })
  return <MacbookBody txt={txt} groupProps={groupProps} />
}

const ImageMacbook = ({ url, groupProps }) => {
  const txt = useTexture(url)
  return <MacbookBody txt={txt} groupProps={groupProps} />
}

const Macbook = ({ texture, ...groupProps }) => {
  const url = texture || DEFAULT_URL
  return isVideoUrl(url) ? (
    <VideoMacbook url={url} groupProps={groupProps} />
  ) : (
    <ImageMacbook url={url} groupProps={groupProps} />
  )
}

useGLTF.preload('/models/computer.glb')
export default Macbook
